production:
  schedule_checks:
    class: ScheduleChecksJob
    priority: 2
    queue: background
    schedule: every minute

development:
  schedule_audits:
    class: ScheduleAuditsJob
    queue: background
    schedule: every minute
